/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package iconsApi2.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Foo service. Represents a row in the &quot;Civica_Foo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>iconsApi2.model.impl.FooModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>iconsApi2.model.impl.FooImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Foo
 * @generated
 */
@ProviderType
public interface FooModel extends BaseModel<Foo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a foo model instance should use the {@link Foo} interface instead.
	 */

	/**
	 * Returns the primary key of this foo.
	 *
	 * @return the primary key of this foo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this foo.
	 *
	 * @param primaryKey the primary key of this foo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this foo.
	 *
	 * @return the uuid of this foo
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this foo.
	 *
	 * @param uuid the uuid of this foo
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this foo.
	 *
	 * @return the foo ID of this foo
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this foo.
	 *
	 * @param fooId the foo ID of this foo
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the nombre of this foo.
	 *
	 * @return the nombre of this foo
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this foo.
	 *
	 * @param nombre the nombre of this foo
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the icono of this foo.
	 *
	 * @return the icono of this foo
	 */
	@AutoEscape
	public String getIcono();

	/**
	 * Sets the icono of this foo.
	 *
	 * @param icono the icono of this foo
	 */
	public void setIcono(String icono);

	/**
	 * Returns the url of this foo.
	 *
	 * @return the url of this foo
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this foo.
	 *
	 * @param url the url of this foo
	 */
	public void setUrl(String url);

}